name: CI

on: [push, workflow_dispatch]

env:
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
    - name: Setup ngrok
      run: |
        .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        .\ngrok\ngrok.exe tcp 3389 &
    - name: Configure RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create User
      run: |
        New-LocalUser "runner" -Password (ConvertTo-SecureString -AsPlainText $Env:USER_PASSWORD -Force)
        Add-LocalGroupMember -Group "Administrators" -Member "runner"
